spring.application.name=EurekaServer

server.port=${PORT:8761}

# Disable self-registration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Important for cloud deployment
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}

# Explicit URL
eureka.client.service-url.defaultZone=https://${RENDER_EXTERNAL_HOSTNAME}/eureka/