spring.application.name=ebankingsubsystem

server.port=8000

spring.datasource.url=jdbc:postgresql://ep-patient-bar-a1xpvxur-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WlkGI5Q4vEmM
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Logger 
logging.level.com.rohan=trace
logging.file.name=logs/app.log

#Eureka Client
eureka.client.service-url.defaultZone=https://horizon-api-y326.onrender.com/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true