spring.application.name=BankAPIGateway
server.port=3333
server.address=0.0.0.0

spring.cloud.gateway.server.webmvc.routes[0].id=core_banking_service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://CORE-BANKING
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/coreBanking/**

spring.cloud.gateway.server.webmvc.routes[1].id=profile_service_route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PROFILE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/profile/**

spring.cloud.gateway.server.webmvc.routes[2].id=utility_service_route
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://UTILITY
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/utility/**

spring.cloud.gateway.server.webmvc.routes[3].id=account_service_route
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ACCOUNTSERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/accounts/**

spring.cloud.gateway.server.webmvc.routes[4].id=beneficiary_service_route
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://BENEFICIARYSERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/beneficiaries/**

spring.cloud.gateway.server.webmvc.routes[5].id=profile_auth_route
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://EBANKINGSUBSYSTEM
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/**

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=https://pratiti-final-project-backend.onrender.com/eureka