spring.application.name=BankAPIGateway
server.port=${PORT:3333}
server.address=0.0.0.0

# ================= CORE BANKING =================
spring.cloud.gateway.server.webmvc.routes[0].id=core_banking_service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://CORE-BANKING
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/coreBanking/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# ================= PROFILE SERVICE =================
spring.cloud.gateway.server.webmvc.routes[1].id=profile_service_route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PROFILE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/profile/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

# ================= UTILITY SERVICE =================
spring.cloud.gateway.server.webmvc.routes[2].id=utility_service_route
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://UTILITY
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/utility/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

# ================= ACCOUNT SERVICE =================
spring.cloud.gateway.server.webmvc.routes[3].id=account_service_route
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ACCOUNTSERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1

# ================= BENEFICIARY SERVICE =================
spring.cloud.gateway.server.webmvc.routes[4].id=beneficiary_service_route
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://BENEFICIARYSERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/beneficiaries/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=StripPrefix=1

# ================= AUTH / ADMIN SERVICE =================
spring.cloud.gateway.server.webmvc.routes[5].id=auth_service_route
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://EBANKINGSUBSYSTEM
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/auth/**,/api/admin/**
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=StripPrefix=1

# ================= EUREKA CONFIG =================
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=https://horizon-api-y326.onrender.com/eureka

# ================= SERVICE DISCOVERY =================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true