spring.application.name=UTILITY

server.port=1113

spring.datasource.url=jdbc:postgresql://ep-blue-field-a1it3v0w-pooler.ap-southeast-1.aws.neon.tech/eBankingSystem?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uvUM26OfiEnH
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=30000

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.tushar=trace

logging.file.name=logs/app.log

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=https://horizon-api-y326.onrender.com/eureka